### ISSUE TITLE
Traceback no relatório de execução de testes automatizados

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/document-store#131]
Ao executar os testes com o comando `python setup.py test`, é exibido o seguinte traceback em meio ao relatório:

```
test_command_remove_metadata (tests.test_services.UpdateDocumentsBundleTest) ... cannot run callback "functools.partial(<function log_change at 0x10ad9f488>, entity='DocumentsBundle')" in response to event "Events.DOCUMENTSBUNDLE_METATADA_UPDATED"
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/document-store/documentstore/interfaces.py", line 87, in notify
    callback(data, self)
  File "/Users/gustavofonseca/prj/document-store/documentstore/services.py", line 425, in log_change
    session.changes.add(change)
  File "/Users/gustavofonseca/prj/document-store/tests/apptesting.py", line 183, in add
    raise exceptions.AlreadyExists()
documentstore.exceptions.AlreadyExists
ok
test_command_success (tests.test_services.UpdateDocumentsBundleTest) ... cannot run callback "functools.partial(<function log_change at 0x10ad9f488>, entity='DocumentsBundle')" in response to event "Events.DOCUMENTSBUNDLE_METATADA_UPDATED"
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/document-store/documentstore/interfaces.py", line 87, in notify
    callback(data, self)
  File "/Users/gustavofonseca/prj/document-store/documentstore/services.py", line 425, in log_change
    session.changes.add(change)
  File "/Users/gustavofonseca/prj/document-store/tests/apptesting.py", line 183, in add
    raise exceptions.AlreadyExists()
documentstore.exceptions.AlreadyExists
ok
test_command_with_unexpected_metadata (tests.test_services.UpdateDocumentsBundleTest) ... cannot run callback "functools.partial(<function log_change at 0x10ad9f488>, entity='DocumentsBundle')" in response to event "Events.DOCUMENTSBUNDLE_METATADA_UPDATED"
Traceback (most recent call last):
  File "/Users/gustavofonseca/prj/document-store/documentstore/interfaces.py", line 87, in notify
    callback(data, self)
  File "/Users/gustavofonseca/prj/document-store/documentstore/services.py", line 425, in log_change
    session.changes.add(change)
  File "/Users/gustavofonseca/prj/document-store/tests/apptesting.py", line 183, in add
    raise exceptions.AlreadyExists()
documentstore.exceptions.AlreadyExists
ok
test_event (tests.test_services.UpdateDocumentsBundleTest) ... ok
```

**Comment by gustavofonseca** [comment]
A exceção `exceptions.AlreadyExists` é lançada pois na não admitimos timestamps duplicados na API de mudanças e provavelmente o código de testes está fixando este valor.
